/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poggers;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;
import tools.CaixaDeDialogo;

/**
 *
 * @author trame
 */
public class Terminal extends javax.swing.JFrame {

    Conta conta1;
    Conta conta2;
    
    public Terminal() {
        initComponents();
        
        conta1 = new Conta(1, 123, "Poggo", 500, 2000);
        
        conta2 = new Conta(2, 656, "Pepe", 12000, 5000);
        
        imprimeConta();
    }
    
    public void imprimeConta(){
        try {
            lblNomeConta1.setText(conta1.getNomePessoa());
            lblSaldoConta1.setText(Tools.formataValor(conta1.getSaldo(), true));
            
            if (conta1.getSaldo() >= 0){
                lblSaldoConta1.setForeground(new java.awt.Color(37, 215, 37));
            } else {
                lblSaldoConta1.setForeground(new java.awt.Color(192, 24, 24));
            }

            lblNomeConta2.setText(conta2.getNomePessoa());
            lblSaldoConta2.setText(Tools.formataValor(conta2.getSaldo(), true));
            
            if (conta2.getSaldo() >= 0){
                lblSaldoConta2.setForeground(new java.awt.Color(37, 215, 37));
            } else {
                lblSaldoConta2.setForeground(new java.awt.Color(192, 24, 24));
            }
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnConta1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNomeConta1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSaldoConta1 = new javax.swing.JLabel();
        txtValorConta1 = new javax.swing.JTextField();
        btnSacarConta1 = new javax.swing.JButton();
        btnDepositarConta1 = new javax.swing.JButton();
        btnTransferirConta1 = new javax.swing.JButton();
        jpnConta2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeConta2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSaldoConta2 = new javax.swing.JLabel();
        txtValorConta2 = new javax.swing.JTextField();
        btnSacarConta2 = new javax.swing.JButton();
        btnDepositarConta2 = new javax.swing.JButton();
        btnTransferirConta2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("terminaunaunow");
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnConta1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Conta 1"));
        jpnConta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Conta");
        jpnConta1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 20));

        lblNomeConta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeConta1.setText("nome");
        jpnConta1.add(lblNomeConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, 20));

        jLabel3.setText("Saldo");
        jpnConta1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        lblSaldoConta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoConta1.setText("R$ XX");
        jpnConta1.add(lblSaldoConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 20));
        jpnConta1.add(txtValorConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 103, 239, -1));

        btnSacarConta1.setText("Sacar");
        btnSacarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta1ActionPerformed(evt);
            }
        });
        jpnConta1.add(btnSacarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, -1, -1));

        btnDepositarConta1.setText("Depositar");
        btnDepositarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta1ActionPerformed(evt);
            }
        });
        jpnConta1.add(btnDepositarConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 143, -1, -1));

        btnTransferirConta1.setText("Transferir");
        btnTransferirConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirConta1ActionPerformed(evt);
            }
        });
        jpnConta1.add(btnTransferirConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 143, -1, -1));

        getContentPane().add(jpnConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 267, 184));

        jpnConta2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true), "Conta 2"));
        jpnConta2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Conta");
        jpnConta2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 20));

        lblNomeConta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeConta2.setText("nome");
        jpnConta2.add(lblNomeConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, 20));

        jLabel4.setText("Saldo");
        jpnConta2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        lblSaldoConta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoConta2.setText("R$ XX");
        jpnConta2.add(lblSaldoConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 20));
        jpnConta2.add(txtValorConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, 243, -1));

        btnSacarConta2.setText("Sacar");
        btnSacarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta2ActionPerformed(evt);
            }
        });
        jpnConta2.add(btnSacarConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, -1, -1));

        btnDepositarConta2.setText("Depositar");
        btnDepositarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta2ActionPerformed(evt);
            }
        });
        jpnConta2.add(btnDepositarConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 143, -1, -1));

        btnTransferirConta2.setText("Transferir");
        btnTransferirConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirConta2ActionPerformed(evt);
            }
        });
        jpnConta2.add(btnTransferirConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 143, -1, -1));

        getContentPane().add(jpnConta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 15, 267, 184));

        jLabel6.setBackground(new java.awt.Color(102, 255, 102));
        jLabel6.setAlignmentY(0.0F);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 579, 214));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta1ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta1.getText());
            if(conta1.sacar(valor)  == true){
//                saque bem sucedido
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque realizado", 'i');
            } else {
//                saque mal sucedido
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque não realizado", 'e');

            }
        
            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnSacarConta1ActionPerformed

    private void btnSacarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta2ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta2.getText());
            if(conta2.sacar(valor)  == true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque realizado", 'i');
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saque não realizado", 'e');
            }
            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnSacarConta2ActionPerformed

    private void btnDepositarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta1ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta1.getText());
            if(conta1.deposito(valor)  == true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Depósito realizado", 'i');
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Depósito não realizado", 'e');
            }
//            conta1.deposito(valor);

            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnDepositarConta1ActionPerformed

    private void btnDepositarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta2ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta2.getText());
            if(conta2.deposito(valor)  == true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Depósito realizado", 'i');
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Depósito não realizado", 'e');
            }
//            conta2.deposito(valor);

            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnDepositarConta2ActionPerformed

    private void btnTransferirConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirConta1ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta1.getText());
            if(conta1.transferir(conta2, valor) == true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Transferência realizada com sucesso!", 'i');
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Transferência não realizada", 'e');
            }
//            conta1.transferir(conta2, valor);

            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnTransferirConta1ActionPerformed

    private void btnTransferirConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirConta2ActionPerformed
        try {
            double valor = Double.parseDouble(txtValorConta2.getText());
            if(conta2.transferir(conta1, valor) == true){
                CaixaDeDialogo.obterinstancia().exibirMensagem("Transferência realizada com sucesso!", 'i');
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Transferência não realizada", 'e');
            }
//            conta1.transferir(conta2, valor);

            imprimeConta();
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
    }//GEN-LAST:event_btnTransferirConta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositarConta1;
    private javax.swing.JButton btnDepositarConta2;
    private javax.swing.JButton btnSacarConta1;
    private javax.swing.JButton btnSacarConta2;
    private javax.swing.JButton btnTransferirConta1;
    private javax.swing.JButton btnTransferirConta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpnConta1;
    private javax.swing.JPanel jpnConta2;
    private javax.swing.JLabel lblNomeConta1;
    private javax.swing.JLabel lblNomeConta2;
    private javax.swing.JLabel lblSaldoConta1;
    private javax.swing.JLabel lblSaldoConta2;
    private javax.swing.JTextField txtValorConta1;
    private javax.swing.JTextField txtValorConta2;
    // End of variables declaration//GEN-END:variables
}
